/* CITY 0 OPS · LIVE-SIM bridge.
   Si el pipeline Gym OS v0 esta corriendo (gym-os/gymos.py demo, API :4781),
   parchea DATA con lo que computa el pipeline y marca el modo LIVE-SIM.
   Si no responde en 900ms, no pasa nada: el demo estatico queda intacto.
   Honestidad: pipeline real, datos SAMPLE; el monitor publico (REAL) no se toca. */

(function () {
  /* el pipeline vive en localhost: en el deploy publico ni se intenta */
  if (!["localhost", "127.0.0.1"].includes(location.hostname)) return;
  const API = "http://127.0.0.1:4781";
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 900);

  fetch(API + "/api/state", { signal: ctrl.signal })
    .then(r => r.json())
    .then(state => {
      clearTimeout(timer);
      if (!state || !state.classes) return;

      /* merge por slice: lo que el pipeline computa pisa lo estatico,
         lo que no manda (p.ej. access.value) se conserva */
      Object.assign(DATA.classes, state.classes);
      Object.assign(DATA.access, state.access);
      Object.assign(DATA.members, state.members);
      if (state.today) Object.assign(DATA.today, state.today);
      if (state.grow) Object.assign(DATA.grow, state.grow);
      if (state.keep) Object.assign(DATA.keep, state.keep);
      if (state.hours) Object.assign(DATA.heatmap, state.hours);
      DATA.live = true;
      DATA.gymos = { meta: state.meta, answers: state.answers, exceptionsOps: state.exceptions_ops };

      injectChip(state.meta);
      wrapExport();
      if (typeof render === "function") render();
      if (typeof toast === "function") toast(
        tr("LIVE-SIM connected", "LIVE-SIM conectado"),
        tr("Classes, Members and Access Control are now computed by the Gym OS pipeline. Simulated data, real API shapes.",
           "Clases, Miembros y Control de Acceso ahora los computa el pipeline Gym OS. Datos simulados, shapes reales del API."));
    })
    .catch(() => { /* pipeline apagado: demo estatico, cero ruido */ });

  function injectChip(meta) {
    if (document.getElementById("livesim")) return;
    const anchor = document.getElementById("side-status");
    if (!anchor) return;
    const el = document.createElement("div");
    el.id = "livesim";
    el.className = "livesim";
    el.innerHTML = `
      <span class="lsdot"></span>
      <span class="lstxt">LIVE-SIM</span>
      <span class="lsdet">${tr("real pipeline, simulated data", "pipeline real, datos simulados")}
        · match ${meta.match_rate}%</span>`;
    el.title = tr("Gym OS v0 pipeline connected on :4781. Glofox fixtures + BioStar simulator, real API shapes.",
                  "Pipeline Gym OS v0 conectado en :4781. Fixtures Glofox + simulador BioStar, shapes reales del API.");
    anchor.insertAdjacentElement("afterend", el);
  }

  function wrapExport() {
    if (typeof exportReport !== "function" || exportReport._live) return;
    const fallback = exportReport;
    const wrapped = function () {
      fetch(API + "/api/morning")
        .then(r => r.text())
        .then(html => {
          const a = document.createElement("a");
          a.href = URL.createObjectURL(new Blob([html], { type: "text/html" }));
          a.download = `city0-ops-morning-report-live.html`;
          document.body.appendChild(a); a.click(); a.remove();
          toast(tr("Live report exported", "Reporte en vivo exportado"),
                tr("Generated by the Gym OS pipeline, not a static mock.",
                   "Generado por el pipeline Gym OS, no un mock estatico."));
        })
        .catch(() => fallback());
    };
    wrapped._live = true;
    window.exportReport = wrapped;
  }
})();
